### ISSUE TITLE
[BUG] Improper implementation of the `randomInt()` function

### ISSUE THREAD

**Issue by gitaalekhyapaul** [Opentek-Org/bookquotes#10]
# Bug Description
The `randomInt()` function implemented is not valid for this use case. The function is shown below:

![Screenshot_20211001_034316](https://user-images.githubusercontent.com/54375111/135537169-39c23846-592a-4756-b1f2-10f65fc82539.png)

As per [W3Schools](https://www.w3schools.com/js/js_random.asp) this generates a random number between `min` and `max` (**BOTH INCLUDED**), which is causing the issue.

Since both `min` and `max` can be included, the code is crashing of index out of bounds error sometimes while testing, when the `randomInt()` returns `max`. A sample screenshot is given below:

![Screenshot_20211001_034241](https://user-images.githubusercontent.com/54375111/135537497-d00a301b-17a3-4941-a23d-f5ef8b45c6f8.png)

**Comment by AnirudhPanda** [comment]
Hey @gitaalekhyapaul 
can you create a separate PR for this please?
