### ISSUE TITLE
Add github actions

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/bookquotes#2]

**Comment by gitaalekhyapaul** [comment]
Hi @AnirudhPanda , can I take up this issue?

**Comment by AnirudhPanda** [comment]
> Hi @AnirudhPanda , can I take up this issue?

Yeah sure!

**Comment by AnirudhPanda** [comment]
> > Hi @AnirudhPanda , can I take up this issue?
> 
> Yeah sure!

**Comment by gitaalekhyapaul** [comment]
@AnirudhPanda , kindly assign me to this :smile:
