### ISSUE TITLE
Use auto labeler to label the issues and PR with Hacktoberfest

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/bookquotes#39]
Use this: https://github.com/marketplace/actions/labeler

**Comment by PrafulAnand** [comment]
hey @AnirudhPanda  can this be closed if the requirements are fulfilled or do you want something else too?

**Comment by AnirudhPanda** [comment]
I don't want to merge the main with v1.0.0 as of now!
Should we create the same thing on v1.0.0 branch?

**Comment by PrafulAnand** [comment]
I can do that , i should branch off from v1.1.0 am i correct?

**Comment by AnirudhPanda** [comment]
> I can do that , i should branch off from v1.1.0 am i correct? also do you want to include your auto assign bot changes and other stuff which you included in main branch yesterday?

No only the labeler!

**Comment by PrafulAnand** [comment]
please review - https://github.com/Opentek-Org/bookquotes/pull/51
